services:
  postgres:
    image: postgres:14.5
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD  
    ports:
    - 5432:5432
    volumes:
     - ./postgres_data:/var/lib/postgresql/data
    env_file:
      ./.env
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80